# Generated by Django 4.2 on 2025-12-18 22:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False,
                                        unique=True)),
                ('name', models.CharField(
                    error_messages={'blank': 'Product name is required.',
                                    'max_length': 'Product name must not exceed 100 characters.'},
                    max_length=100)),
                ('shop', models.CharField(
                    error_messages={'blank': 'Shop name is required.',
                                    'max_length': 'Shop name must not exceed 50 characters.'},
                    max_length=50)),
                ('price', models.PositiveIntegerField(error_messages={
                    'invalid': 'Price must be greater than zero.'})),
                ('sku', models.CharField(
                    error_messages={'blank': 'SKU is required.',
                                    'max_length': 'SKU must not exceed 20 characters.'},
                    max_length=20)),
                ('description', models.TextField(error_messages={
                    'blank': 'Product description is required.'})),
                ('location', models.CharField(
                    error_messages={'blank': 'Product location is required.',
                                    'max_length': 'Location must not exceed 50 characters.'},
                    max_length=50)),
                ('category', models.CharField(
                    error_messages={'blank': 'Category is required.',
                                    'max_length': 'Category must not exceed 50 characters.'},
                    max_length=50)),
                ('stock', models.PositiveIntegerField(error_messages={
                    'invalid': 'Stock must be zero or greater.'})),
                ('is_available', models.BooleanField(default=False)),
                ('picture', models.URLField(
                    error_messages={'invalid': 'Picture must be a valid URL.',
                                    'max_length': 'Picture URL must not exceed 500 characters.'},
                    max_length=500)),
            ],
        ),
    ]
