# Generated by Django 4.2 on 2025-12-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(error_messages={'invalid': 'Stock must be zero or greater.'}),
        ),
    ]
